title: Not a place :3
author: Lzu Tao
email: lzutao@example.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: lzutao
github_username:  lzutao

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
